title: 徐文志程序猿
author: xuwenzhi
email: xuwenzhi7@gmail.com
description: >
  Web程序猿，专注系统架构设计及性能优化。

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://xuwenzhi.com" # the base hostname & protocol for your site, e.g. http://example.com

website: http://www.xuwenzhi.com
github_username:  xuwenzhi
twitter_username: xuwenzhi
facebook_username: xuwenzhi
stackoverflow_username: xuwenzhi # (developer story)


collections:
  - setup

# disqus:
#   shortname:

# Minimaless date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minimaless:
  date_format: "%b %-d, %Y"
preview_posts: true
permalink: /:title
paginate: 10 # increase this value to reflect how many posts per page you want
paginate_path: "/page:num/"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - _pages/about.md
  - _pages/contact.md
  - _pages/github.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

markdown: kramdown
theme: minimaless
# remote_theme: brettinternet/minimaless # uncomment to allow GitHub to build for GitHub Pages - https://github.com/blog/2464-use-any-theme-with-github-pages

include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
